import { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabase';
import { FaHourglassHalf, FaCheck } from 'react-icons/fa';

export default function MimicaPlayControls() {
  const [session, setSession] = useState<any>(null);
  const [gameState, setGameState] = useState<any>(null);
  const [player, setPlayer] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [teamPlayers, setTeamPlayers] = useState<any[]>([]);
  const [currentWord, setCurrentWord] = useState<string>('');

  const playerId = typeof window !== 'undefined' ? localStorage.getItem('mimica_player_id') : null;
  const urlParams = typeof window !== 'undefined' ? new URLSearchParams(window.location.search) : null;
  const sessionId = urlParams?.get('session_id');

  useEffect(() => {
    if (!playerId || !sessionId) {
      window.location.href = '/mimica';
      return;
    }

    fetchInitialData();

    // Subscribe to session changes
    const sessionSub = supabase.channel(`mimica_session_client_${sessionId}`)
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'mimica_sessions' }, (payload) => {
         if (payload.new.id === sessionId) {
            setSession(payload.new);
         }
      }).subscribe();

    // Subscribe to game state changes
    const gsSub = supabase.channel(`mimica_gs_client_${sessionId}`)
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'mimica_game_state' }, (payload) => {
         if (payload.new.session_id === sessionId) {
            setGameState(payload.new);
         }
      }).subscribe();
      
    // Subscribe to player changes
    const playersSub = supabase.channel(`mimica_players_client_${sessionId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'mimica_players' }, async (p) => {
         if (p.new?.session_id === sessionId || p.old?.session_id === sessionId) {
             const { data: newTp } = await supabase.from('mimica_players').select('*').eq('session_id', sessionId).order('joined_at', { ascending: true });
             if (newTp) {
                 const tId = newTp.find(player => player.id === playerId)?.team_id;
                 if (tId) setTeamPlayers(newTp.filter(player => player.team_id === tId));
             }
         }
      }).subscribe();

    return () => {
      supabase.removeChannel(sessionSub);
      supabase.removeChannel(stateSub);
      supabase.removeChannel(playersSub);
    };
  }, []);

  const fetchInitialData = async () => {
    try {
      // Get Player
      const { data: pData, error: pErr } = await supabase.from('mimica_players').select('*').eq('id', playerId).single();
      if (pErr) throw pErr;
      setPlayer(pData);

      // Get Session
      const { data: sData, error: sErr } = await supabase.from('mimica_sessions').select('*').eq('id', sessionId).single();
      if (sErr) throw sErr;
      setSession(sData);

      // Get Game State
      const { data: gsData } = await supabase.from('mimica_game_state').select('*').eq('session_id', sessionId).single();
      if (gsData) setGameState(gsData);

      // Get Team Players
      if (pData) {
         const { data: tpData } = await supabase.from('mimica_players').select('*').eq('session_id', sessionId).eq('team_id', pData.team_id).order('joined_at', { ascending: true });
         if (tpData) setTeamPlayers(tpData);
      }

      setLoading(false);
    } catch (err: any) {
      setError(err.message || 'Error loading game data');
      setLoading(false);
    }
  };

  // Whenever game state changes, fetch the current word based on the indices from the game state.
  // Wait, the client needs the word list. It's better if the client fetches the word list and stores it, or the app updates the game_state with the actual word string.
  // We'll add current_word_text to mimica_game_state to make it easier.
  // I will just use current_word_index and fetch from the word array if needed, but since the words are randomly generated by the admin app, it's safer if the admin app updates current_word_text in the database.
  // But our schema doesn't have current_word_text.
  // For now, let's assume the admin app sets an 'active_word' in the game state table. Let's alter the schema implicitly by using it here, and I'll update the table via the admin app.
  
  const handlePass = async () => {
    if (!gameState) return;
    // Add 30 seconds to time_elapsed_seconds
    await supabase.from('mimica_game_state').update({
       time_elapsed_seconds: gameState.time_elapsed_seconds + 30,
       // We don't advance the word yet, the admin app needs to be notified?
       // Wait, the user said: "un boton para psar por si no lo adivinan pasara y aumentara 30 segundos extra... y pasara al siguiente integrante"
       // So clicking Pass means it's WRONG, adds 30 seconds, and moves to next player AND next word.
       // The best way to handle this securely is to have a new table `mimica_actions` that the admin listens to, or we let the client do the update.
       // For simplicity, the client will just insert an action in a `mimica_actions` table, and the admin app handles the logic.
       // OR we can just update the game_state directly here if the client knows the next player.
       // Let's create an 'action' column in game_state: action_trigger
    });
    // Let's use a simpler approach. Insert a row in a generic `mimica_actions` table if we need to, but let's just let the admin app listen to changes in game_state.
    // Actually, I can just update a 'last_action' column in game_state so the admin app can process it.
    await supabase.from('mimica_game_state').update({
       updated_at: new Date().toISOString()
    });
    
    // Simpler: The client will emit an event or update a field `pass_requested: true` or `correct_requested: true` in game_state.
  };

  if (loading) return <div className="min-h-screen bg-[#111219] text-white flex items-center justify-center font-bold">Cargando...</div>;
  if (error) return <div className="min-h-screen bg-[#111219] text-red-500 flex items-center justify-center font-bold">{error}</div>;
  if (!session || !player) return null;

  // Render logic based on status
  if (session.status === 'waiting') {
    const playerIndex = teamPlayers.findIndex(p => p.id === playerId);
    return (
      <div className="flex flex-col items-center justify-center min-h-screen p-6 bg-[#111219] text-center">
         <h2 className="text-2xl font-black text-white mb-4 uppercase">Esperando a los demás...</h2>
         <p className="text-orange-400 font-bold mb-4">Eres parte del Equipo {player.team_id}</p>
         {playerIndex !== -1 && (
            <div className="bg-orange-500/20 text-orange-300 py-2 px-6 rounded-full border border-orange-500/50 inline-block font-black uppercase tracking-wider mb-4">
               Tú eres el Jugador #{playerIndex + 1}
            </div>
         )}
         <div className="mt-8 animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-orange-500"></div>
      </div>
    );
  }

  if (session.status === 'prep') {
    const playerIndex = teamPlayers.findIndex(p => p.id === playerId);
    return (
      <div className="flex flex-col items-center justify-center min-h-screen p-6 bg-[#111219] text-center">
         <h2 className="text-3xl font-black text-white mb-4 uppercase text-orange-500">¡Prepárate!</h2>
         <p className="text-gray-300 font-bold text-lg">El equipo {session.active_team} va a comenzar en breve.</p>
         {session.active_team === player.team_id && (
            <p className="mt-4 text-xl font-black text-green-400 animate-pulse">¡ES EL TURNO DE TU EQUIPO!</p>
         )}
         {playerIndex !== -1 && (
            <div className="mt-4 text-orange-400 font-bold uppercase">Eres el Jugador #{playerIndex + 1}</div>
         )}
      </div>
    );
  }

  if (session.status === 'playing' && gameState) {
     const isMyTeam = session.active_team === player.team_id;
     const amIMimer = gameState.active_mimer_id === player.id;
     const amIValidator = gameState.active_validator_id === player.id;
     const playerIndex = teamPlayers.findIndex(p => p.id === playerId);

     if (isMyTeam) {
        if (amIMimer) {
           return (
             <div className="flex flex-col items-center justify-center min-h-screen p-6 bg-[#111219] text-center">
                <h2 className="text-2xl font-black text-gray-400 mb-2 uppercase">Tu turno de hacer mímica</h2>
                {playerIndex !== -1 && <p className="text-orange-400 font-bold uppercase text-sm mb-4">Jugador #{playerIndex + 1}</p>}
                <div className="bg-white/10 p-8 rounded-2xl border-4 border-orange-500 shadow-[0_0_30px_rgba(249,115,22,0.3)] my-8 w-full max-w-sm">
                   <h1 className="text-5xl font-black text-white uppercase tracking-widest break-words">
                     {gameState.current_word || '...'}
                   </h1>
                </div>
                <button 
                  onClick={async () => {
                     await supabase.from('mimica_game_state').update({ pass_requested: true }).eq('id', gameState.id);
                  }}
                  className="btn-3d-purple w-full max-w-sm py-4 text-2xl uppercase tracking-widest mt-4"
                >
                  Pasar (+30s)
                </button>
             </div>
           );
        } else {
           return (
             <div className="flex flex-col items-center justify-center min-h-screen p-6 bg-[#111219] text-center">
                <h2 className="text-2xl font-black text-white mb-2 uppercase">Espera tu turno</h2>
                {playerIndex !== -1 && <p className="text-orange-400 font-bold uppercase text-sm mb-4">Jugador #{playerIndex + 1}</p>}
                <p className="text-gray-400 font-bold">Alguien más de tu equipo está haciendo mímica ahora.</p>
                <div className="mt-8 animate-pulse text-orange-500 text-6xl">
                  <FaHourglassHalf />
                </div>
             </div>
           );
        }
     } else {
        if (amIValidator) {
           return (
             <div className="flex flex-col items-center justify-center min-h-screen p-6 bg-[#111219] text-center">
                <h2 className="text-xl font-black text-green-400 mb-2 uppercase">ERES EL VALIDADOR</h2>
                <p className="text-sm text-gray-400 mb-6 font-bold">Verifica si el equipo adivina esta palabra:</p>
                <div className="bg-white/10 p-8 rounded-2xl border-4 border-green-500 shadow-[0_0_30px_rgba(34,197,94,0.3)] my-4 w-full max-w-sm">
                   <h1 className="text-4xl font-black text-white uppercase tracking-widest break-words">
                     {gameState.current_word || '...'}
                   </h1>
                </div>
                <button 
                  onClick={async () => {
                     await supabase.from('mimica_game_state').update({ correct_requested: true }).eq('id', gameState.id);
                  }}
                  className="btn-3d-green w-full max-w-sm py-4 text-2xl uppercase tracking-widest mt-8 flex items-center justify-center gap-2"
                >
                  <FaCheck /> ¡Correcto!
                </button>
             </div>
           );
        } else {
           return (
             <div className="flex flex-col items-center justify-center min-h-screen p-6 bg-[#111219] text-center">
                <h2 className="text-2xl font-black text-white mb-4 uppercase">Equipo {session.active_team} está jugando</h2>
                <p className="text-gray-400 font-bold">Espera a que termine su turno.</p>
             </div>
           );
        }
     }
  }

  if (session.status === 'round_end' || session.status === 'finished') {
     return (
       <div className="flex flex-col items-center justify-center min-h-screen p-6 bg-[#111219] text-center">
          <h2 className="text-3xl font-black text-white mb-4 uppercase text-yellow-400">¡Tiempo finalizado!</h2>
          <p className="text-gray-300 font-bold">Mira la pantalla principal para ver los resultados.</p>
       </div>
     );
  }

  return null;
}
